export const btnArr = [
  {src: 'clear',id: 'clear',fn:'clear',},
  {src: 'blank_l',id: '(',fn:'change',},
  {src: 'blank_r',id: ')',fn:'change',},
  {src: 'divide',id: '/',fn:'change',},
  {src: '7',id: '7',fn:'change',},
  {src: '8',id: '8',fn:'change',},
  {src: '9',id: '9',fn:'change',},
  {src: 'multi',id: '*',fn:'change',},
  {src: '4',id: '4',fn:'change',},
  {src: '5',id: '5',fn:'change',},
  {src: '6',id: '6',fn:'change',},
  {src: 'minus',id: '-',fn:'change',},
  {src: '1',id: '1',fn:'change',},
  {src: '2',id: '2',fn:'change',},
  {src: '3',id: '3',fn:'change',},
  {src: 'plus',id: '+',fn:'change',},
  {src: 'del',id: 'del',fn:'delete',},
  {src: '0',id: '0',fn:'change',},
  {src: 'dot',id: '.',fn:'change',},
  {src: 'equal',id: 'calc',fn:'calc',},
]